#Makefile.base

MKDIR_P:= mkdir -p
CFLAGS?=-O0 -g -Wall  -DNDEBUG -std=gnu11
CC:=gcc

# build output directories
DIRS+=$(addprefix $(TARGET)/,$(USEMODULE))
OBJS+=$(obj-y)
SRCS+=$(src-y)

# build objects

$(APPLICATION): \
	$(DIRS) \
	$(OBJS)

${DIRS}:
	${MKDIR_P} ${DIRS}

$(OBJS):$(SRCS)
	@echo "  CC $@"
	@${CC} -c ${CFLAGS} ${LDFLAGS} $< -o $@ 
