#Makefile.include
MODULE:=libucrypto/secp256k1/uecc
LIB:=libucrypto-secp256k1-uecc.a
SRC:=$(BASE)/$(MODULE)
SRCS+=$(SRC)/uecc.c
INCS+=$(BASE)/$(MODULE)
INCS+=$(BASE)/external/secp256k1/include
include $(BASE)/Makefile.common
